//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLGiangVien
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChiTietPhieuDay
    {
        public int MaChiTiet { get; set; }
        public string MaLopHP { get; set; }
        public Nullable<int> MaHK { get; set; }
        public string TenMH { get; set; }
        public string CaKip { get; set; }
        public Nullable<int> SiSo { get; set; }
        public string Bac { get; set; }
        public string GV1 { get; set; }
        public string GV2 { get; set; }
        public Nullable<int> MaPhieuBD { get; set; }
    
        public virtual PhieuBaoDay PhieuBaoDay { get; set; }
    }
}
