//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLGiangVien
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class QLGV_DBEntities : DbContext
    {
        public QLGV_DBEntities()
            : base("name=QLGV_DBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<BoMon> BoMons { get; set; }
        public virtual DbSet<ChiTietPhieuDay> ChiTietPhieuDays { get; set; }
        public virtual DbSet<ChucDanh> ChucDanhs { get; set; }
        public virtual DbSet<GiangVien> GiangViens { get; set; }
        public virtual DbSet<GiangVien_LopHocPhan> GiangVien_LopHocPhan { get; set; }
        public virtual DbSet<GiangVien_TTGiangDay> GiangVien_TTGiangDay { get; set; }
        public virtual DbSet<HocKy> HocKies { get; set; }
        public virtual DbSet<HocKy_LopHocPhan> HocKy_LopHocPhan { get; set; }
        public virtual DbSet<Khoa> Khoas { get; set; }
        public virtual DbSet<MienGiam> MienGiams { get; set; }
        public virtual DbSet<MonHoc> MonHocs { get; set; }
        public virtual DbSet<PhanQuyen> PhanQuyens { get; set; }
        public virtual DbSet<PhieuBaoDay> PhieuBaoDays { get; set; }
        public virtual DbSet<QCBacDaoTao> QCBacDaoTaos { get; set; }
        public virtual DbSet<QCCaKip> QCCaKips { get; set; }
        public virtual DbSet<QCCaKip_LopHocPhan> QCCaKip_LopHocPhan { get; set; }
        public virtual DbSet<QCChamThi> QCChamThis { get; set; }
        public virtual DbSet<QCNgonNgu> QCNgonNgus { get; set; }
        public virtual DbSet<QCSiSo> QCSiSoes { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<TaiKhoan_PDT> TaiKhoan_PDT { get; set; }
        public virtual DbSet<ThanhToanGiangDay> ThanhToanGiangDays { get; set; }
    }
}
