//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLGiangVien
{
    using System;
    using System.Collections.Generic;
    
    public partial class GiangVien_LopHocPhan
    {
        public int MaHK { get; set; }
        public string MaLopHP { get; set; }
        public string MaGV { get; set; }
        public Nullable<bool> LoaiGV { get; set; }
        public Nullable<int> SoTietDay { get; set; }
    
        public virtual GiangVien GiangVien { get; set; }
        public virtual HocKy_LopHocPhan HocKy_LopHocPhan { get; set; }
    }
}
