//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLGiangVien
{
    using System;
    using System.Collections.Generic;
    
    public partial class GiangVien_TTGiangDay
    {
        public int MaPhieuTT { get; set; }
        public string MaGV { get; set; }
        public Nullable<decimal> DonGia { get; set; }
        public Nullable<int> DinhMuc { get; set; }
        public Nullable<int> MienGiam { get; set; }
        public Nullable<int> SoLopDay { get; set; }
        public Nullable<float> TaiThucTe { get; set; }
    
        public virtual GiangVien GiangVien { get; set; }
        public virtual ThanhToanGiangDay ThanhToanGiangDay { get; set; }
    }
}
