//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLGiangVien
{
    using System;
    using System.Collections.Generic;
    
    public partial class GiangVien
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public GiangVien()
        {
            this.GiangVien_LopHocPhan = new HashSet<GiangVien_LopHocPhan>();
            this.GiangVien_TTGiangDay = new HashSet<GiangVien_TTGiangDay>();
            this.MienGiams = new HashSet<MienGiam>();
        }
    
        public string MaGV { get; set; }
        public string HoTen { get; set; }
        public string SDT { get; set; }
        public string Email { get; set; }
        public string GioiTinh { get; set; }
        public string DiaChi { get; set; }
        public string TenTK_GV { get; set; }
        public string MatKhau { get; set; }
        public string ChucVu { get; set; }
        public string MaBM { get; set; }
        public string MaCD { get; set; }
        public Nullable<int> MaPQ { get; set; }
    
        public virtual BoMon BoMon { get; set; }
        public virtual ChucDanh ChucDanh { get; set; }
        public virtual PhanQuyen PhanQuyen { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GiangVien_LopHocPhan> GiangVien_LopHocPhan { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GiangVien_TTGiangDay> GiangVien_TTGiangDay { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MienGiam> MienGiams { get; set; }
    }
}
