//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLGiangVien
{
    using System;
    using System.Collections.Generic;
    
    public partial class HocKy_LopHocPhan
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public HocKy_LopHocPhan()
        {
            this.GiangVien_LopHocPhan = new HashSet<GiangVien_LopHocPhan>();
            this.QCCaKip_LopHocPhan = new HashSet<QCCaKip_LopHocPhan>();
        }
    
        public int MaHK { get; set; }
        public string MaLopHP { get; set; }
        public string TenLop { get; set; }
        public string GiangDuong { get; set; }
        public Nullable<int> SiSo { get; set; }
        public Nullable<int> TietHoc { get; set; }
        public Nullable<int> MaQCNN { get; set; }
        public Nullable<int> MaQCDT { get; set; }
        public Nullable<int> MaQCCT { get; set; }
        public Nullable<int> MaQCSS { get; set; }
        public string MaMH { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GiangVien_LopHocPhan> GiangVien_LopHocPhan { get; set; }
        public virtual QCChamThi QCChamThi { get; set; }
        public virtual QCBacDaoTao QCBacDaoTao { get; set; }
        public virtual QCNgonNgu QCNgonNgu { get; set; }
        public virtual QCSiSo QCSiSo { get; set; }
        public virtual MonHoc MonHoc { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<QCCaKip_LopHocPhan> QCCaKip_LopHocPhan { get; set; }
    }
}
