//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLGiangVien
{
    using System;
    using System.Collections.Generic;
    
    public partial class QCCaKip_LopHocPhan
    {
        public string MaLopHP { get; set; }
        public int MaHK { get; set; }
        public int MaQCCK { get; set; }
        public string Thu { get; set; }
        public Nullable<int> TietBatDau { get; set; }
        public Nullable<int> TietKetThuc { get; set; }
    
        public virtual HocKy_LopHocPhan HocKy_LopHocPhan { get; set; }
        public virtual QCCaKip QCCaKip { get; set; }
    }
}
