//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLGiangVien
{
    using System;
    using System.Collections.Generic;
    
    public partial class TaiKhoan_PDT
    {
        public string TenTK_PDT { get; set; }
        public string MatKhau { get; set; }
        public string HoTenNguoiDung { get; set; }
        public Nullable<int> LoaiBoPhan { get; set; }
        public string TenBoPhan { get; set; }
        public Nullable<int> MaPQ { get; set; }
    
        public virtual PhanQuyen PhanQuyen { get; set; }
    }
}
